
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const user_Role = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type user_Role = (typeof user_Role)[keyof typeof user_Role]
